if (CMAKE_COMPILER_IS_GNUCC)

	set(RSN_BASE_C_FLAGS      "-Wall")
	set(CMAKE_C_FLAGS         "${CMAKE_C_FLAGS} ${RSN_BASE_C_FLAGS} -DPROJECT_VERSION=\"${PROJECT_VERSION}\"")
	set(CMAKE_C_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG} ${RSN_BASE_C_FLAGS} -ggdb")
	set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} ${RSN_BASE_C_FLAGS}")

    if (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_GNU_SOURCE -std=c99 -pedantic -D_HAVE_TIMERFD")
    endif()
	if(APPLE)
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_BSD_SOURCE")
	endif(APPLE)

endif(CMAKE_COMPILER_IS_GNUCC)

