# Try to find the libczmq
#
# LIBCZMQ_FOUND       - system has the libczmq library
# LIBCZMQ_LIBRARIES   - The libraries needed to use libczmq

FIND_LIBRARY(LIBCZMQ_LIBRARY NAMES czmq libczmq PATH /usr/lib /usr/local/lib)

IF(LIBCZMQ_LIBRARY)
	SET(LIBCZMQ_FOUND 1)
	SET(LIBCZMQ_LIBRARIES ${LIBCZMQ_LIBRARY})
ELSE (LIBCZMQ_LIBRARY)
	SET(LIBCZMQ_FOUND 0)
	SET(LIBCZMQ_LIBRARIES)
ENDIF (LIBCZMQ_LIBRARY)

# Report the results.
IF (NOT LIBCZMQ_FOUND)
	SET(LIBCZMQ_DIR_MESSAGE "Libczmq was not found.")
	IF (NOT LIBCZMQ_FIND_QUIETLY)
		MESSAGE(STATUS "${LIBCZMQ_DIR_MESSAGE}")
	ELSE (NOT LIBCZMQ_FIND_QUIETLY)
		IF (LIBCZMQ_FIND_REQUIRED)
			MESSAGE(FATAL_ERROR "${LIBCZMQ_DIR_MESSAGE}")
		ENDIF (LIBCZMQ_FIND_REQUIRED)
	ENDIF (NOT LIBCZMQ_FIND_QUIETLY)
ENDIF (NOT LIBCZMQ_FOUND)

MARK_AS_ADVANCED(
	LIBCZMQ_LIBRARY
)
