# Try to find the libzmq
#
# LIBZMQ_FOUND       - system has the libzmq library
# LIBZMQ_LIBRARIES   - The libraries needed to use libzmq


FIND_LIBRARY(LIBZMQ_LIBRARY NAMES zmq libzmq PATH /usr/lib /usr/local/lib)

IF(LIBZMQ_LIBRARY)
	SET(LIBZMQ_FOUND 1)
	SET(LIBZMQ_LIBRARIES ${LIBZMQ_LIBRARY})
ELSE (LIBZMQ_LIBRARY)
	SET(LIBZMQ_FOUND 0)
	SET(LIBZMQ_LIBRARIES)
ENDIF (LIBZMQ_LIBRARY)

# Report the results.
IF (NOT LIBZMQ_FOUND)
	SET(LIBZMQ_DIR_MESSAGE "Libzmq was not found.")
	IF (NOT LIBZMQ_FIND_QUIETLY)
		MESSAGE(STATUS "${LIBZMQ_DIR_MESSAGE}")
	ELSE (NOT LIBZMQ_FIND_QUIETLY)
		IF (LIBZMQ_FIND_REQUIRED)
			MESSAGE(FATAL_ERROR "${LIBZMQ_DIR_MESSAGE}")
		ENDIF (LIBZMQ_FIND_REQUIRED)
	ENDIF (NOT LIBZMQ_FIND_QUIETLY)
ENDIF (NOT LIBZMQ_FOUND)

MARK_AS_ADVANCED(
	LIBZMQ_LIBRARY
)
